service: web-app-deployment-poc

frameworkVersion: '2'


provider:
  name: aws
  runtime: python3.7
  lambdaHashingVersion: 20201221
  region: us-east-2
  deploymentBucket: deployment-poc-ci-cd
  profile: deployment_poc

functions:
  get_all_authors:
    handler: handler.getallauthors
    role: RoleForGetAllAuthors

  get_all_courses:
    handler: handler.getallcourses
    role: RoleForGetAllCourses

  add_course:
    handler: handler.addcourse
    role: RoleForAddCourse

resources:
  Resources:
    RoleForGetAllAuthors:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: RV_deployment_poc_getallauthors
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: RV_deploymentpoc_getallauthors-cloudwatch-logs-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:CreateLogGroup
                    - logs:PutLogEvents
                  Resource: "*"

          - PolicyName: RV_deploymentpoc_getallauthors-dynamodb-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "dynamodb:Scan"
                  Resource:
                      - "arn:aws:dynamodb:us-east-2:390618173518:table/RV_Deployment_POC_Authors"

    RoleForGetAllCourses:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: RV_deployment_poc_getallcourses
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: RV_deploymentpoc_getallcourses-cloudwatch-logs-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:CreateLogGroup
                    - logs:PutLogEvents
                  Resource: "*"

          - PolicyName: RV_deploymentpoc_getallcourses-dynamodb-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "dynamodb:Scan"
                  Resource:
                    - "arn:aws:dynamodb:us-east-2:390618173518:table/RV_Deployment_POC_Courses"

    RoleForAddCourse:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: RV_deployment_poc_addcourse
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: RV_deploymentpoc_addcourse-cloudwatch-logs-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:CreateLogGroup
                    - logs:PutLogEvents
                  Resource: "*"

          - PolicyName: RV_deploymentpoc_addcourse-dynamodb-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "dynamodb:Scan"
                    - "dynamodb:PutItem"
                  Resource:
                    - "arn:aws:dynamodb:us-east-2:390618173518:table/RV_Deployment_POC_Courses"