service: api

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage}
  lambdaHashingVersion: 20201221
  region: us-east-2
  deploymentBucket: deployment-poc-ci-cd
  environment:
    env_stage: ${self:provider.stage}
    ddb_table_name: ${self:provider.stage}_course

functions:
  get_all_courses:
    handler: handler.getallcourses
    role: RoleForGetAllCourses

  add_course:
    handler: handler.addcourse
    role: RoleForAddCourse

resources:
  Resources:
    RoleForGetAllCourses:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: RV_deployment_poc_${self:provider.stage}_getallcourses
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: RV_deployment_poc_${self:provider.stage}_getallcourses-cloudwatch-logs-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:CreateLogGroup
                    - logs:PutLogEvents
                  Resource: "*"

          - PolicyName: RV_deployment_poc_${self:provider.stage}_getallcourses-dynamodb-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "dynamodb:Scan"
                  Resource:
                    - "arn:aws:dynamodb:us-east-2:390618173518:table/${self:provider.stage}_course"

    RoleForAddCourse:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: RV_deployment_poc_${self:provider.stage}_addcourse
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: RV_deployment_poc_${self:provider.stage}_addcourse-cloudwatch-logs-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:CreateLogGroup
                    - logs:PutLogEvents
                  Resource: "*"

          - PolicyName: RV_deployment_poc_${self:provider.stage}_addcourse-dynamodb-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "dynamodb:Scan"
                    - "dynamodb:PutItem"
                  Resource:
                    - "arn:aws:dynamodb:us-east-2:390618173518:table/${self:provider.stage}_course"