service: sls-deployment-poc

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: us-east-2
  deploymentBucket: deployment-poc-ci-cd

functions:
  hello:
    handler: handler.hello
